### PR TITLE
Converting float64 to int

### PR DESCRIPTION
**Pull request by denilsonsa**
Fixes compilation error which seems to be broken since 32d1e2ef80813ba9e88c187ced84f2b04b9a116e

Sidenote: the `rotating_cube` demo displays as red blinking characters in my terminal. Something is likely wrong with escape codes. Maybe the code should move away from `termbox-go` to a newer library.

### CODE REVIEW

**Comment by Kerrigan29a** [comment]
Thank you very much for the bugfix and sorry for the delay in the reply.
